### ISSUE TITLE
下载种子 已经无效，但是否可以考虑直接生成磁力链？

### ISSUE THREAD

**Issue by rya-icu** [NanYoMy/DHT-woodworm#6]
从peers_request中获取的info_hash能不能直接用来做magnet中的btih值？？

类似magent:?xt=urn:btih:1231231231231231231231231231321

**Comment by NanYoMy** [comment]
就是这么做的。下载种子的再写一个吧，应为使用的网站已经被墙了。我也很久没用过这个网站了。
